INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (101, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (102, 16, 'OPE-MAN-102', 'workforce-management-high-impact-managed-service-102', 'Managed Service', 'manage', 'Ongoing', NULL, NULL, 'medium', 'TMaaS Managed Delivery', 'Manage', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (96, 1, 102, 'active', 'buy_now', 95);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (96, 'list', NULL, 'Custom Monthly Plans', 'monthly', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (102, 'Managed workforce operations, scheduling optimisation, monitoring, support, reporting, and continuous workforce improvement services.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (102, 'Architecture alignment for Workforce Management (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (102, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (102, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (102, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (102, 'manage');
INSERT INTO product_tags (variant_id, tag_name) VALUES (102, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (102, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (102, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (102, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (102, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (102, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (102, 'Phase 4: Operational Handover', 3);
INSERT INTO products (id, slug, title, short_description, collection_id, is_high_impact, audience, industry_relevance, department, business_impact, status) VALUES (17, 'enterprise-data-platform-high-impact', 'Enterprise Data Platform (High-Impact)', 'Assessment of enterprise data maturity, governance capabilities, operational data quality, platform readiness, and data transformation opportunities.', 'ai', true, 'Enterprise & Mid-Market', 'Cross-Industry', 'IT & Transformation', 'Significant operational improvements and risk reduction.', 'published');
INSERT INTO product_category_map (product_id, category_id) VALUES (17, 'modernise-technology') ON CONFLICT DO NOTHING;
INSERT INTO product_category_map (product_id, category_id) VALUES (17, 'improve-operations') ON CONFLICT DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (103, 17, 'AI-ADV-103', 'enterprise-data-platform-high-impact-assess-103', 'Assess', 'advisory', '1 Week', 1, 1, 'medium', 'TMaaS Managed Delivery', 'Advisory', '(High-Impact) Positioning Strategy', true, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (97, 1, 103, 'active', 'free', 100);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (97, 'list', 0, 'Free', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (103, 'Assessment of enterprise data maturity, governance capabilities, operational data quality, platform readiness, and data transformation opportunities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (103, 'Architecture alignment for Enterprise Data Platform (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (103, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (103, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (103, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (103, 'data');
INSERT INTO product_tags (variant_id, tag_name) VALUES (103, 'advisory');
INSERT INTO product_tags (variant_id, tag_name) VALUES (103, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (103, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (103, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (103, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (103, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (103, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (104, 17, 'AI-DES-104', 'enterprise-data-platform-high-impact-design-104', 'Design', 'design', '4 Weeks', 4, 4, 'high', 'TMaaS Managed Delivery', 'Design', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (98, 1, 104, 'active', 'buy_now', 99);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (98, 'from', 1000, 'From $1,000', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (104, 'Design of enterprise data architectures, governance frameworks, data pipelines, operational data models, and scalable data platform strategies.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (104, 'Architecture alignment for Enterprise Data Platform (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (104, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (104, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (104, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (104, 'data');
INSERT INTO product_tags (variant_id, tag_name) VALUES (104, 'design');
INSERT INTO product_tags (variant_id, tag_name) VALUES (104, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (104, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (104, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (104, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (104, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (104, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (105, 17, 'AI-AI_-105', 'enterprise-data-platform-high-impact-ai-design-105', 'AI Design', 'ai_design', '4 Weeks', 4, 4, 'high', 'TMaaS Managed Delivery', 'Ai Design', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (99, 1, 105, 'active', 'buy_now', 98);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (99, 'from', 1000, 'From $1,000', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (105, 'Design of AI-ready data capabilities including intelligent pipelines, automated governance, metadata intelligence, vector architectures, and operational data automation.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (105, 'Architecture alignment for Enterprise Data Platform (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (105, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (105, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (105, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (105, 'data');
INSERT INTO product_tags (variant_id, tag_name) VALUES (105, 'ai_design');
INSERT INTO product_tags (variant_id, tag_name) VALUES (105, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (105, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (105, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (105, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (105, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (105, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (106, 17, 'AI-DEP-106', 'enterprise-data-platform-high-impact-implementation-106', 'Implementation', 'deploy', '12 Weeks', 12, 12, 'high', 'TMaaS Managed Delivery', 'Deploy', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (100, 1, 106, 'active', 'request_quote', 97);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (100, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (106, 'Deployment and implementation of enterprise data platforms, data pipelines, governance environments, operational data ecosystems, and scalable analytics foundations.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (106, 'Architecture alignment for Enterprise Data Platform (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (106, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (106, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (106, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (106, 'data');
INSERT INTO product_tags (variant_id, tag_name) VALUES (106, 'deploy');
INSERT INTO product_tags (variant_id, tag_name) VALUES (106, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (106, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (106, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (106, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (106, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (106, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (107, 17, 'AI-AI_-107', 'enterprise-data-platform-high-impact-ai-implementation-107', 'AI Implementation', 'ai_deploy', '12 Weeks', 12, 12, 'high', 'TMaaS Managed Delivery', 'Ai Deploy', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (101, 1, 107, 'active', 'request_quote', 96);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (101, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (107, 'Deployment of AI-powered data automation, intelligent governance, metadata intelligence, operational data orchestration, and AI-ready platform capabilities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (107, 'Architecture alignment for Enterprise Data Platform (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (107, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (107, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (107, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (107, 'data');
INSERT INTO product_tags (variant_id, tag_name) VALUES (107, 'ai_deploy');
INSERT INTO product_tags (variant_id, tag_name) VALUES (107, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (107, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (107, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (107, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (107, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (107, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (108, 17, 'AI-MAN-108', 'enterprise-data-platform-high-impact-managed-service-108', 'Managed Service', 'manage', 'Ongoing', NULL, NULL, 'medium', 'TMaaS Managed Delivery', 'Manage', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (102, 1, 108, 'active', 'buy_now', 95);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (102, 'list', NULL, 'Custom Monthly Plans', 'monthly', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (108, 'Managed data platform operations, governance monitoring, optimisation, support, reporting, and continuous enterprise data improvement services.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (108, 'Architecture alignment for Enterprise Data Platform (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (108, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (108, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (108, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (108, 'data');
INSERT INTO product_tags (variant_id, tag_name) VALUES (108, 'manage');
INSERT INTO product_tags (variant_id, tag_name) VALUES (108, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (108, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (108, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (108, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (108, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (108, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (108, 'Phase 4: Operational Handover', 3);
INSERT INTO products (id, slug, title, short_description, collection_id, is_high_impact, audience, industry_relevance, department, business_impact, status) VALUES (18, 'business-intelligence-analytics-high-impact', 'Business Intelligence & Analytics (High-Impact)', 'Assessment of reporting maturity, decision intelligence capabilities, analytics readiness, operational visibility, and enterprise intelligence opportunities.', 'ai', true, 'Enterprise & Mid-Market', 'Cross-Industry', 'IT & Transformation', 'Significant operational improvements and risk reduction.', 'published');
INSERT INTO product_category_map (product_id, category_id) VALUES (18, 'modernise-technology') ON CONFLICT DO NOTHING;
INSERT INTO product_category_map (product_id, category_id) VALUES (18, 'improve-operations') ON CONFLICT DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (109, 18, 'AI-ADV-109', 'business-intelligence-analytics-high-impact-assess-109', 'Assess', 'advisory', '1 Week', 1, 1, 'medium', 'TMaaS Managed Delivery', 'Advisory', '(High-Impact) Positioning Strategy', true, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (103, 1, 109, 'active', 'free', 100);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (103, 'list', 0, 'Free', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (109, 'Assessment of reporting maturity, decision intelligence capabilities, analytics readiness, operational visibility, and enterprise intelligence opportunities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (109, 'Architecture alignment for Business Intelligence & Analytics (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (109, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (109, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (109, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (109, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (109, 'advisory');
INSERT INTO product_tags (variant_id, tag_name) VALUES (109, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (109, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (109, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (109, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (109, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (109, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (110, 18, 'AI-DES-110', 'business-intelligence-analytics-high-impact-design-110', 'Design', 'design', '4 Weeks', 4, 4, 'high', 'TMaaS Managed Delivery', 'Design', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (104, 1, 110, 'active', 'buy_now', 99);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (104, 'from', 1000, 'From $1,000', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (110, 'Design of business intelligence frameworks, KPI models, analytics workflows, forecasting environments, executive reporting structures, and operational intelligence strategies.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (110, 'Architecture alignment for Business Intelligence & Analytics (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (110, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (110, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (110, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (110, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (110, 'design');
INSERT INTO product_tags (variant_id, tag_name) VALUES (110, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (110, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (110, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (110, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (110, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (110, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (111, 18, 'AI-AI_-111', 'business-intelligence-analytics-high-impact-ai-design-111', 'AI Design', 'ai_design', '4 Weeks', 4, 4, 'high', 'TMaaS Managed Delivery', 'Ai Design', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (105, 1, 111, 'active', 'buy_now', 98);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (105, 'from', 1000, 'From $1,000', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (111, 'Design of AI-powered analytics capabilities including predictive intelligence, intelligent forecasting, process intelligence, anomaly detection, and operational analytics automation.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (111, 'Architecture alignment for Business Intelligence & Analytics (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (111, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (111, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (111, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (111, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (111, 'ai_design');
INSERT INTO product_tags (variant_id, tag_name) VALUES (111, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (111, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (111, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (111, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (111, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (111, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (112, 18, 'AI-DEP-112', 'business-intelligence-analytics-high-impact-implementation-112', 'Implementation', 'deploy', '12 Weeks', 12, 12, 'high', 'TMaaS Managed Delivery', 'Deploy', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (106, 1, 112, 'active', 'request_quote', 97);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (106, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (112, 'Deployment and implementation of analytics platforms, reporting systems, executive dashboards, operational intelligence environments, and enterprise analytics capabilities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (112, 'Architecture alignment for Business Intelligence & Analytics (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (112, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (112, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (112, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (112, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (112, 'deploy');
INSERT INTO product_tags (variant_id, tag_name) VALUES (112, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (112, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (112, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (112, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (112, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (112, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (113, 18, 'AI-AI_-113', 'business-intelligence-analytics-high-impact-ai-implementation-113', 'AI Implementation', 'ai_deploy', '12 Weeks', 12, 12, 'high', 'TMaaS Managed Delivery', 'Ai Deploy', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (107, 1, 113, 'active', 'request_quote', 96);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (107, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (113, 'Deployment of AI-powered analytics automation, predictive intelligence, forecasting environments, anomaly detection, and intelligent reporting capabilities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (113, 'Architecture alignment for Business Intelligence & Analytics (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (113, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (113, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (113, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (113, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (113, 'ai_deploy');
INSERT INTO product_tags (variant_id, tag_name) VALUES (113, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (113, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (113, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (113, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (113, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (113, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (114, 18, 'AI-MAN-114', 'business-intelligence-analytics-high-impact-managed-service-114', 'Managed Service', 'manage', 'Ongoing', NULL, NULL, 'medium', 'TMaaS Managed Delivery', 'Manage', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (108, 1, 114, 'active', 'buy_now', 95);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (108, 'list', NULL, 'Custom Monthly Plans', 'monthly', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (114, 'Managed analytics operations, dashboard optimisation, reporting support, monitoring, operational intelligence management, and continuous analytics improvement services.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (114, 'Architecture alignment for Business Intelligence & Analytics (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (114, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (114, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (114, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (114, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (114, 'manage');
INSERT INTO product_tags (variant_id, tag_name) VALUES (114, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (114, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (114, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (114, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (114, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (114, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (114, 'Phase 4: Operational Handover', 3);
INSERT INTO products (id, slug, title, short_description, collection_id, is_high_impact, audience, industry_relevance, department, business_impact, status) VALUES (19, 'enterprise-ai-automation-high-impact', 'Enterprise AI & Automation (High-Impact)', 'Strategic assessment of AI readiness, automation opportunities, operational intelligence maturity, and enterprise AI transformation potential.', 'ai', true, 'Enterprise & Mid-Market', 'Cross-Industry', 'IT & Transformation', 'Significant operational improvements and risk reduction.', 'published');
INSERT INTO product_category_map (product_id, category_id) VALUES (19, 'modernise-technology') ON CONFLICT DO NOTHING;
INSERT INTO product_category_map (product_id, category_id) VALUES (19, 'improve-operations') ON CONFLICT DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (115, 19, 'AI-ADV-115', 'enterprise-ai-automation-high-impact-assess-115', 'Assess', 'advisory', '1 Week', 1, 1, 'medium', 'TMaaS Managed Delivery', 'Advisory', '(High-Impact) Positioning Strategy', true, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (109, 1, 115, 'active', 'free', 100);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (109, 'list', 0, 'Free', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (115, 'Strategic assessment of AI readiness, automation opportunities, operational intelligence maturity, and enterprise AI transformation potential.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (115, 'Architecture alignment for Enterprise AI & Automation (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (115, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (115, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (115, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (115, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (115, 'advisory');
INSERT INTO product_tags (variant_id, tag_name) VALUES (115, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (115, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (115, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (115, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (115, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (115, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (116, 19, 'AI-DES-116', 'enterprise-ai-automation-high-impact-design-116', 'Design', 'design', '4 Weeks', 4, 4, 'high', 'TMaaS Managed Delivery', 'Design', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (110, 1, 116, 'active', 'buy_now', 99);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (110, 'from', 1000, 'From $1,000', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (116, 'Design of enterprise AI operating models, intelligent automation architectures, AI assistants, agents, copilots, and cognitive operational workflows.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (116, 'Architecture alignment for Enterprise AI & Automation (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (116, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (116, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (116, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (116, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (116, 'design');
INSERT INTO product_tags (variant_id, tag_name) VALUES (116, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (116, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (116, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (116, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (116, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (116, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (117, 19, 'AI-AI_-117', 'enterprise-ai-automation-high-impact-ai-design-117', 'AI Design', 'ai_design', '4 Weeks', 4, 4, 'high', 'TMaaS Managed Delivery', 'Ai Design', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (111, 1, 117, 'active', 'buy_now', 98);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (111, 'from', 1000, 'From $1,000', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (117, 'Design of advanced AI ecosystems including agents, copilots, PromptOps, ModelOps, knowledge architectures, automation frameworks, and intelligent orchestration environments.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (117, 'Architecture alignment for Enterprise AI & Automation (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (117, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (117, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (117, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (117, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (117, 'ai_design');
INSERT INTO product_tags (variant_id, tag_name) VALUES (117, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (117, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (117, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (117, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (117, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (117, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (118, 19, 'AI-DEP-118', 'enterprise-ai-automation-high-impact-implementation-118', 'Implementation', 'deploy', '12 Weeks', 12, 12, 'high', 'TMaaS Managed Delivery', 'Deploy', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (112, 1, 118, 'active', 'request_quote', 97);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (112, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (118, 'Deployment and implementation of enterprise AI platforms, intelligent assistants, operational automation environments, and AI-driven business capabilities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (118, 'Architecture alignment for Enterprise AI & Automation (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (118, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (118, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (118, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (118, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (118, 'deploy');
INSERT INTO product_tags (variant_id, tag_name) VALUES (118, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (118, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (118, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (118, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (118, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (118, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (119, 19, 'AI-AI_-119', 'enterprise-ai-automation-high-impact-ai-implementation-119', 'AI Implementation', 'ai_deploy', '12 Weeks', 12, 12, 'high', 'TMaaS Managed Delivery', 'Ai Deploy', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (113, 1, 119, 'active', 'request_quote', 96);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (113, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (119, 'Deployment of advanced AI agents, intelligent copilots, cognitive automation frameworks, AI orchestration environments, and enterprise operational intelligence capabilities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (119, 'Architecture alignment for Enterprise AI & Automation (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (119, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (119, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (119, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (119, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (119, 'ai_deploy');
INSERT INTO product_tags (variant_id, tag_name) VALUES (119, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (119, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (119, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (119, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (119, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (119, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (120, 19, 'AI-MAN-120', 'enterprise-ai-automation-high-impact-managed-service-120', 'Managed Service', 'manage', 'Ongoing', NULL, NULL, 'medium', 'TMaaS Managed Delivery', 'Manage', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (114, 1, 120, 'active', 'buy_now', 95);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (114, 'list', NULL, 'Custom Monthly Plans', 'monthly', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (120, 'Managed AI operations, monitoring, optimization, governance, model lifecycle management, operational intelligence support, and continuous AI improvement services.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (120, 'Architecture alignment for Enterprise AI & Automation (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (120, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (120, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (120, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (120, 'ai');
INSERT INTO product_tags (variant_id, tag_name) VALUES (120, 'manage');
INSERT INTO product_tags (variant_id, tag_name) VALUES (120, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (120, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (120, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (120, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (120, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (120, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (120, 'Phase 4: Operational Handover', 3);
INSERT INTO products (id, slug, title, short_description, collection_id, is_high_impact, audience, industry_relevance, department, business_impact, status) VALUES (20, 'technology-governance-high-impact', 'Technology Governance (High-Impact)', 'Assessment of technology governance maturity, architecture controls, standards compliance, operational assurance, and enterprise governance opportunities.', 'security', true, 'Enterprise & Mid-Market', 'Cross-Industry', 'IT & Transformation', 'Significant operational improvements and risk reduction.', 'published');
INSERT INTO product_category_map (product_id, category_id) VALUES (20, 'modernise-technology') ON CONFLICT DO NOTHING;
INSERT INTO product_category_map (product_id, category_id) VALUES (20, 'improve-operations') ON CONFLICT DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (121, 20, 'SEC-ADV-121', 'technology-governance-high-impact-assess-121', 'Assess', 'advisory', '1 Week', 1, 1, 'medium', 'TMaaS Managed Delivery', 'Advisory', '(High-Impact) Positioning Strategy', true, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (115, 1, 121, 'active', 'free', 100);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (115, 'list', 0, 'Free', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (121, 'Assessment of technology governance maturity, architecture controls, standards compliance, operational assurance, and enterprise governance opportunities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (121, 'Architecture alignment for Technology Governance (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (121, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (121, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (121, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (121, 'security');
INSERT INTO product_tags (variant_id, tag_name) VALUES (121, 'advisory');
INSERT INTO product_tags (variant_id, tag_name) VALUES (121, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (121, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (121, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (121, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (121, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (121, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (122, 20, 'SEC-DES-122', 'technology-governance-high-impact-design-122', 'Design', 'design', '4 Weeks', 4, 4, 'high', 'TMaaS Managed Delivery', 'Design', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (116, 1, 122, 'active', 'buy_now', 99);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (116, 'from', 1000, 'From $1,000', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (122, 'Design of governance frameworks, architecture standards, operational controls, compliance structures, assurance environments, and enterprise governance strategies.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (122, 'Architecture alignment for Technology Governance (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (122, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (122, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (122, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (122, 'security');
INSERT INTO product_tags (variant_id, tag_name) VALUES (122, 'design');
INSERT INTO product_tags (variant_id, tag_name) VALUES (122, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (122, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (122, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (122, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (122, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (122, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (123, 20, 'SEC-AI_-123', 'technology-governance-high-impact-ai-design-123', 'AI Design', 'ai_design', '4 Weeks', 4, 4, 'high', 'TMaaS Managed Delivery', 'Ai Design', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (117, 1, 123, 'active', 'buy_now', 98);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (117, 'from', 1000, 'From $1,000', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (123, 'Design of AI-powered governance capabilities including intelligent compliance monitoring, policy automation, operational assurance analytics, and governance intelligence.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (123, 'Architecture alignment for Technology Governance (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (123, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (123, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (123, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (123, 'security');
INSERT INTO product_tags (variant_id, tag_name) VALUES (123, 'ai_design');
INSERT INTO product_tags (variant_id, tag_name) VALUES (123, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (123, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (123, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (123, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (123, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (123, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (124, 20, 'SEC-DEP-124', 'technology-governance-high-impact-implementation-124', 'Implementation', 'deploy', '12 Weeks', 12, 12, 'high', 'TMaaS Managed Delivery', 'Deploy', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (118, 1, 124, 'active', 'request_quote', 97);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (118, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (124, 'Deployment and implementation of governance platforms, architecture control environments, standards management systems, compliance capabilities, and assurance frameworks.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (124, 'Architecture alignment for Technology Governance (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (124, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (124, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (124, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (124, 'security');
INSERT INTO product_tags (variant_id, tag_name) VALUES (124, 'deploy');
INSERT INTO product_tags (variant_id, tag_name) VALUES (124, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (124, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (124, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (124, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (124, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (124, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (125, 20, 'SEC-AI_-125', 'technology-governance-high-impact-ai-implementation-125', 'AI Implementation', 'ai_deploy', '12 Weeks', 12, 12, 'high', 'TMaaS Managed Delivery', 'Ai Deploy', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (119, 1, 125, 'active', 'request_quote', 96);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (119, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (125, 'Deployment of AI-powered governance automation, intelligent compliance monitoring, operational assurance analytics, predictive governance, and standards intelligence capabilities.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (125, 'Architecture alignment for Technology Governance (High-Impact)', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (125, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (125, 'SLA-backed governance and reporting', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (125, 'Phased delivery and milestone tracking', 3);
INSERT INTO product_tags (variant_id, tag_name) VALUES (125, 'security');
INSERT INTO product_tags (variant_id, tag_name) VALUES (125, 'ai_deploy');
INSERT INTO product_tags (variant_id, tag_name) VALUES (125, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (125, 'high-impact');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (125, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (125, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (125, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (125, 'Phase 4: Operational Handover', 3);
