INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (228, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (228, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (228, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (229, 27, 'OPE-BUN-229', 'hospitality-operations-high-impact-transformation-bundle-229', 'Transformation Bundle', 'bundle', '16-24 Weeks', 16, 24, 'high', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (213, 1, 229, 'active', 'request_quote', 200);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (213, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (229, 'End-to-end transformation bundle for Hospitality Operations.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (229, 'Includes Design, AI Design, Implementation, AI Implementation, and Managed Services', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (229, 'Architecture alignment', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (229, 'Dedicated TMaaS specialist team', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (229, 'SLA-backed governance and reporting', 3);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (229, 'Phased delivery and milestone tracking', 4);
INSERT INTO product_tags (variant_id, tag_name) VALUES (229, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (229, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (229, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (229, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (229, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (229, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (229, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (229, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (230, 28, 'OPE-BUN-230', 'retail-operations-high-impact-transformation-bundle-230', 'Transformation Bundle', 'bundle', '16-24 Weeks', 16, 24, 'high', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (214, 1, 230, 'active', 'request_quote', 200);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (214, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (230, 'End-to-end transformation bundle for Retail Operations.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (230, 'Includes Design, AI Design, Implementation, AI Implementation, and Managed Services', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (230, 'Architecture alignment', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (230, 'Dedicated TMaaS specialist team', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (230, 'SLA-backed governance and reporting', 3);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (230, 'Phased delivery and milestone tracking', 4);
INSERT INTO product_tags (variant_id, tag_name) VALUES (230, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (230, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (230, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (230, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (230, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (230, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (230, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (230, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (231, 29, 'OPE-BUN-231', 'service-operations-high-impact-transformation-bundle-231', 'Transformation Bundle', 'bundle', '16-24 Weeks', 16, 24, 'high', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (215, 1, 231, 'active', 'request_quote', 200);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (215, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (231, 'End-to-end transformation bundle for Service Operations.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (231, 'Includes Design, AI Design, Implementation, AI Implementation, and Managed Services', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (231, 'Architecture alignment', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (231, 'Dedicated TMaaS specialist team', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (231, 'SLA-backed governance and reporting', 3);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (231, 'Phased delivery and milestone tracking', 4);
INSERT INTO product_tags (variant_id, tag_name) VALUES (231, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (231, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (231, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (231, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (231, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (231, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (231, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (231, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (232, 30, 'OPE-BUN-232', 'logistics-operations-high-impact-transformation-bundle-232', 'Transformation Bundle', 'bundle', '16-24 Weeks', 16, 24, 'high', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (216, 1, 232, 'active', 'request_quote', 200);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (216, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (232, 'End-to-end transformation bundle for Logistics Operations.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (232, 'Includes Design, AI Design, Implementation, AI Implementation, and Managed Services', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (232, 'Architecture alignment', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (232, 'Dedicated TMaaS specialist team', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (232, 'SLA-backed governance and reporting', 3);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (232, 'Phased delivery and milestone tracking', 4);
INSERT INTO product_tags (variant_id, tag_name) VALUES (232, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (232, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (232, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (232, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (232, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (232, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (232, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (232, 'Phase 4: Operational Handover', 3);
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (233, 31, 'OPE-BUN-233', 'wellness-operations-high-impact-transformation-bundle-233', 'Transformation Bundle', 'bundle', '16-24 Weeks', 16, 24, 'high', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (217, 1, 233, 'active', 'request_quote', 200);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (217, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (233, 'End-to-end transformation bundle for Wellness Operations.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (233, 'Includes Design, AI Design, Implementation, AI Implementation, and Managed Services', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (233, 'Architecture alignment', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (233, 'Dedicated TMaaS specialist team', 2);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (233, 'SLA-backed governance and reporting', 3);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (233, 'Phased delivery and milestone tracking', 4);
INSERT INTO product_tags (variant_id, tag_name) VALUES (233, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (233, 'transformation');
INSERT INTO product_tags (variant_id, tag_name) VALUES (233, 'high-impact');
INSERT INTO product_tags (variant_id, tag_name) VALUES (233, 'operations');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (233, 'Phase 1: Discovery & Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (233, 'Phase 2: Execution', 1);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (233, 'Phase 3: Governance & Review', 2);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (233, 'Phase 4: Operational Handover', 3);
INSERT INTO products (id, slug, title, short_description, collection_id, is_high_impact, audience, industry_relevance, department, business_impact, status) VALUES (32, 'advisory-set', 'Advisory Set', 'Customisable Advisory capability spanning one or more categories.', 'operations', false, 'Enterprise & Mid-Market', 'Cross-Industry', 'IT & Transformation', 'Broad organizational alignment and enablement.', 'published');
INSERT INTO product_category_map (product_id, category_id) VALUES (32, 'modernise-technology') ON CONFLICT DO NOTHING;
INSERT INTO product_category_map (product_id, category_id) VALUES (32, 'improve-operations') ON CONFLICT DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (234, 32, 'OPE-BUN-234', 'advisory-set-advisory-set-234', 'Advisory Set', 'bundle', 'Variable', NULL, NULL, 'medium', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (218, 1, 234, 'active', 'request_quote', 150);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (218, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (234, 'Customisable Advisory capability spanning one or more categories.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (234, 'Customisable selection across categories', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (234, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (234, 'SLA-backed governance and reporting', 2);
INSERT INTO product_tags (variant_id, tag_name) VALUES (234, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (234, 'set');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (234, 'Phase 1: Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (234, 'Phase 2: Execution', 1);
INSERT INTO products (id, slug, title, short_description, collection_id, is_high_impact, audience, industry_relevance, department, business_impact, status) VALUES (33, 'design-services-set', 'Design Services set', 'Customisable Design capability spanning one or more categories.', 'operations', false, 'Enterprise & Mid-Market', 'Cross-Industry', 'IT & Transformation', 'Broad organizational alignment and enablement.', 'published');
INSERT INTO product_category_map (product_id, category_id) VALUES (33, 'modernise-technology') ON CONFLICT DO NOTHING;
INSERT INTO product_category_map (product_id, category_id) VALUES (33, 'improve-operations') ON CONFLICT DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (235, 33, 'OPE-BUN-235', 'design-services-set-design-services-set-235', 'Design Services set', 'bundle', 'Variable', NULL, NULL, 'medium', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (219, 1, 235, 'active', 'request_quote', 150);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (219, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (235, 'Customisable Design capability spanning one or more categories.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (235, 'Customisable selection across categories', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (235, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (235, 'SLA-backed governance and reporting', 2);
INSERT INTO product_tags (variant_id, tag_name) VALUES (235, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (235, 'set');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (235, 'Phase 1: Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (235, 'Phase 2: Execution', 1);
INSERT INTO products (id, slug, title, short_description, collection_id, is_high_impact, audience, industry_relevance, department, business_impact, status) VALUES (34, 'deploy-services-set', 'Deploy Services set', 'Customisable Deploy capability spanning one or more categories.', 'operations', false, 'Enterprise & Mid-Market', 'Cross-Industry', 'IT & Transformation', 'Broad organizational alignment and enablement.', 'published');
INSERT INTO product_category_map (product_id, category_id) VALUES (34, 'modernise-technology') ON CONFLICT DO NOTHING;
INSERT INTO product_category_map (product_id, category_id) VALUES (34, 'improve-operations') ON CONFLICT DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (236, 34, 'OPE-BUN-236', 'deploy-services-set-deploy-services-set-236', 'Deploy Services set', 'bundle', 'Variable', NULL, NULL, 'medium', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (220, 1, 236, 'active', 'request_quote', 150);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (220, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (236, 'Customisable Deploy capability spanning one or more categories.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (236, 'Customisable selection across categories', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (236, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (236, 'SLA-backed governance and reporting', 2);
INSERT INTO product_tags (variant_id, tag_name) VALUES (236, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (236, 'set');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (236, 'Phase 1: Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (236, 'Phase 2: Execution', 1);
INSERT INTO products (id, slug, title, short_description, collection_id, is_high_impact, audience, industry_relevance, department, business_impact, status) VALUES (35, 'managed-services-set', 'Managed Services set', 'Customisable Managed capability spanning one or more categories.', 'operations', false, 'Enterprise & Mid-Market', 'Cross-Industry', 'IT & Transformation', 'Broad organizational alignment and enablement.', 'published');
INSERT INTO product_category_map (product_id, category_id) VALUES (35, 'modernise-technology') ON CONFLICT DO NOTHING;
INSERT INTO product_category_map (product_id, category_id) VALUES (35, 'improve-operations') ON CONFLICT DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, slug, variant_name, service_type_id, duration_display, duration_weeks_min, duration_weeks_max, delivery_complexity, implementation_model, badge, positioning, is_default_variant, status) VALUES (237, 35, 'OPE-BUN-237', 'managed-services-set-managed-services-set-237', 'Managed Services set', 'bundle', 'Variable', NULL, NULL, 'medium', 'TMaaS Managed Delivery', 'Bundle', '(High-Impact) Positioning Strategy', false, 'published');
INSERT INTO marketplace_listings (id, merchant_id, variant_id, listing_status, purchasability, popularity_score) VALUES (221, 1, 237, 'active', 'request_quote', 150);
INSERT INTO variant_prices (listing_id, price_type, amount, price_display, billing_period, is_current) VALUES (221, 'custom_floor', NULL, 'Custom', 'one_time', true);
INSERT INTO product_content (variant_id, description, positioning) VALUES (237, 'Customisable Managed capability spanning one or more categories.', '(High-Impact) Positioning Strategy');
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (237, 'Customisable selection across categories', 0);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (237, 'Dedicated TMaaS specialist team', 1);
INSERT INTO product_features (variant_id, feature_text, sort_order) VALUES (237, 'SLA-backed governance and reporting', 2);
INSERT INTO product_tags (variant_id, tag_name) VALUES (237, 'bundle');
INSERT INTO product_tags (variant_id, tag_name) VALUES (237, 'set');
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (237, 'Phase 1: Alignment', 0);
INSERT INTO product_timeline_milestones (variant_id, milestone_text, sort_order) VALUES (237, 'Phase 2: Execution', 1);
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (203, 2, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (203, 3, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (203, 4, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (203, 5, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (203, 6, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (204, 8, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (204, 9, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (204, 10, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (204, 11, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (204, 12, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (205, 14, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (205, 15, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (205, 16, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (205, 17, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (205, 18, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (206, 20, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (206, 21, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (206, 22, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (206, 23, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (206, 24, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (207, 26, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (207, 27, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (207, 28, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (207, 29, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (207, 30, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (208, 32, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (208, 33, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (208, 34, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (208, 35, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (208, 36, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (209, 38, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (209, 39, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (209, 40, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (209, 41, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (209, 42, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (210, 44, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (210, 45, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (210, 46, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (210, 47, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (210, 48, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (211, 50, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (211, 51, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (211, 52, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (211, 53, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (211, 54, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (212, 56, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (212, 57, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (212, 58, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (212, 59, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (212, 60, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (213, 62, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (213, 63, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (213, 64, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (213, 65, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (213, 66, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (214, 74, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (214, 75, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (214, 76, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (214, 77, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (214, 78, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (215, 80, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (215, 81, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (215, 82, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (215, 83, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (215, 84, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (216, 86, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (216, 87, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (216, 88, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (216, 89, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (216, 90, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (217, 92, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (217, 93, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (217, 94, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (217, 95, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (217, 96, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (218, 98, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (218, 99, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (218, 100, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (218, 101, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (218, 102, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (219, 104, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (219, 105, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (219, 106, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (219, 107, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (219, 108, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (220, 110, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (220, 111, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (220, 112, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (220, 113, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (220, 114, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (221, 116, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (221, 117, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (221, 118, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (221, 119, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (221, 120, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (222, 122, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (222, 123, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (222, 124, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (222, 125, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (222, 126, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (223, 128, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (223, 129, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (223, 130, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (223, 131, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (223, 132, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (224, 134, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (224, 135, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (224, 136, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (224, 137, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (224, 138, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (225, 150, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (225, 151, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (225, 152, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (225, 153, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (225, 154, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (226, 156, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (226, 157, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (226, 158, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (226, 159, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (226, 160, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (227, 162, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (227, 163, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (227, 164, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (227, 165, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (227, 166, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (228, 168, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (228, 169, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (228, 170, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (228, 171, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (228, 172, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (229, 174, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (229, 175, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (229, 176, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (229, 177, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (229, 178, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (230, 180, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (230, 181, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (230, 182, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (230, 183, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (230, 184, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (231, 186, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (231, 187, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (231, 188, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (231, 189, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (231, 190, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (232, 192, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (232, 193, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (232, 194, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (232, 195, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (232, 196, 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (233, 198, 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (233, 199, 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (233, 200, 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (233, 201, 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_items (bundle_variant_id, included_variant_id, sort_order) VALUES (233, 202, 4) ON CONFLICT DO NOTHING;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (4, 'Website CMS', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Page management', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'Website CMS' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Component-based content editing', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'Website CMS' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Multi-site management', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'Website CMS' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Media library', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'Website CMS' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Content approval workflows', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'Website CMS' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (4, 'Digital Experience Portal', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Personalised landing pages', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'Digital Experience Portal' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer dashboards', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'Digital Experience Portal' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Portal navigation management', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'Digital Experience Portal' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Role-based access', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'Digital Experience Portal' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Multi-device responsiveness', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'Digital Experience Portal' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (4, 'Content Publishing Engine', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Scheduled publishing', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'Content Publishing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Draft/version management', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'Content Publishing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Content localisation', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'Content Publishing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign publishing', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'Content Publishing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Dynamic content rendering', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'Content Publishing Engine' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (4, 'SEO & Performance Suite', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'SEO optimisation', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Metadata management', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Performance monitoring', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Accessibility compliance', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Search indexing', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (4, 'Customer Interaction Layer', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Live chat integration', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Contact forms', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'CTA management', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer feedback capture', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Session tracking', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (4, 'Forms & Conversion Engine', 5);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Digital forms', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Lead capture', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Form validation', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workflow routing', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Conversion analytics', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (10, 'Social Publishing Hub', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Multi-channel publishing', 0 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Publishing Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Content scheduling', 1 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Publishing Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Approval workflows', 2 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Publishing Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Asset management', 3 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Publishing Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Hashtag management', 4 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Publishing Hub' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (10, 'Community Engagement Console', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Comment management', 0 FROM deploy_modules WHERE variant_id = 10 AND name = 'Community Engagement Console' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Direct message management', 1 FROM deploy_modules WHERE variant_id = 10 AND name = 'Community Engagement Console' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer response workflows', 2 FROM deploy_modules WHERE variant_id = 10 AND name = 'Community Engagement Console' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Escalation routing', 3 FROM deploy_modules WHERE variant_id = 10 AND name = 'Community Engagement Console' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Moderation controls', 4 FROM deploy_modules WHERE variant_id = 10 AND name = 'Community Engagement Console' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (10, 'Campaign Management', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign planning', 0 FROM deploy_modules WHERE variant_id = 10 AND name = 'Campaign Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audience targeting', 1 FROM deploy_modules WHERE variant_id = 10 AND name = 'Campaign Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Budget tracking', 2 FROM deploy_modules WHERE variant_id = 10 AND name = 'Campaign Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign automation', 3 FROM deploy_modules WHERE variant_id = 10 AND name = 'Campaign Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Engagement monitoring', 4 FROM deploy_modules WHERE variant_id = 10 AND name = 'Campaign Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (10, 'Social Listening Dashboard', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Brand monitoring', 0 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Listening Dashboard' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Keyword tracking', 1 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Listening Dashboard' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Sentiment analysis', 2 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Listening Dashboard' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Competitor monitoring', 3 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Listening Dashboard' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Trend tracking', 4 FROM deploy_modules WHERE variant_id = 10 AND name = 'Social Listening Dashboard' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (10, 'Engagement Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Engagement reporting', 0 FROM deploy_modules WHERE variant_id = 10 AND name = 'Engagement Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audience insights', 1 FROM deploy_modules WHERE variant_id = 10 AND name = 'Engagement Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Reach analytics', 2 FROM deploy_modules WHERE variant_id = 10 AND name = 'Engagement Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Conversion tracking', 3 FROM deploy_modules WHERE variant_id = 10 AND name = 'Engagement Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign performance dashboards', 4 FROM deploy_modules WHERE variant_id = 10 AND name = 'Engagement Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (16, 'Mobile Application Platform', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Native/hybrid app deployment', 0 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Application Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'App navigation', 1 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Application Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Offline mode support', 2 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Application Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Multi-platform support', 3 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Application Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'App configuration management', 4 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Application Platform' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (16, 'Push Notification Engine', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Push messaging', 0 FROM deploy_modules WHERE variant_id = 16 AND name = 'Push Notification Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign notifications', 1 FROM deploy_modules WHERE variant_id = 16 AND name = 'Push Notification Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Behaviour-triggered notifications', 2 FROM deploy_modules WHERE variant_id = 16 AND name = 'Push Notification Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Scheduling', 3 FROM deploy_modules WHERE variant_id = 16 AND name = 'Push Notification Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Notification analytics', 4 FROM deploy_modules WHERE variant_id = 16 AND name = 'Push Notification Engine' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (16, 'Mobile Identity Layer', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Mobile authentication', 0 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Identity Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Biometric login', 1 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Identity Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'MFA support', 2 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Identity Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Session management', 3 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Identity Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Device registration', 4 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Identity Layer' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (16, 'Customer Mobile Services', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Profile management', 0 FROM deploy_modules WHERE variant_id = 16 AND name = 'Customer Mobile Services' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Mobile transactions', 1 FROM deploy_modules WHERE variant_id = 16 AND name = 'Customer Mobile Services' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'In-app messaging', 2 FROM deploy_modules WHERE variant_id = 16 AND name = 'Customer Mobile Services' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Support integration', 3 FROM deploy_modules WHERE variant_id = 16 AND name = 'Customer Mobile Services' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Self-service actions', 4 FROM deploy_modules WHERE variant_id = 16 AND name = 'Customer Mobile Services' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (16, 'Mobile Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'App usage analytics', 0 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Crash monitoring', 1 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer journey tracking', 2 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Performance analytics', 3 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Behaviour insights', 4 FROM deploy_modules WHERE variant_id = 16 AND name = 'Mobile Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (22, 'Channel Orchestration', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Cross-channel workflows', 0 FROM deploy_modules WHERE variant_id = 22 AND name = 'Channel Orchestration' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Journey continuity', 1 FROM deploy_modules WHERE variant_id = 22 AND name = 'Channel Orchestration' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Interaction routing', 2 FROM deploy_modules WHERE variant_id = 22 AND name = 'Channel Orchestration' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Engagement triggers', 3 FROM deploy_modules WHERE variant_id = 22 AND name = 'Channel Orchestration' LIMIT 1;
