INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'SEO optimisation', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Metadata management', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Performance monitoring', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Accessibility compliance', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Search indexing', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'SEO & Performance Suite' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (4, 'Customer Interaction Layer', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Live chat integration', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Contact forms', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'CTA management', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer feedback capture', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Session tracking', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'Customer Interaction Layer' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (4, 'Forms & Conversion Engine', 5);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Digital forms', 0 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Lead capture', 1 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Form validation', 2 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workflow routing', 3 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Conversion analytics', 4 FROM deploy_modules WHERE variant_id = 4 AND name = 'Forms & Conversion Engine' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Collaboration Workspace', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Team workspaces', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'File collaboration', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Shared calendars', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Meeting integration', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workspace permissions', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Employee Communication Hub', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Announcements', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Internal messaging', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Employee engagement feeds', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Notifications', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Broadcast communications', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Knowledge Workspace', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Knowledge repositories', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Document management', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Search capabilities', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Knowledge sharing', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Content governance', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Task & Activity Management', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Task assignment', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workflow tracking', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Activity monitoring', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Team coordination', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Productivity tracking', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Workplace Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Usage reporting', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Collaboration analytics', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Engagement insights', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Productivity dashboards', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Adoption monitoring', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Data Integration Platform', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'ETL/ELT pipelines', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'API integrations', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data synchronisation', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Batch processing', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Real-time streaming', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Data Governance Hub', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data catalogues', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data lineage', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Access controls', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data quality monitoring', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Governance workflows', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Data Warehouse', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Centralised storage', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data modelling', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Query optimisation', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Historical data management', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data partitioning', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Master Data Management', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Golden record management', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data standardisation', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Duplicate management', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Entity resolution', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Reference data management', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Data Analytics Workspace', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Query workspaces', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data exploration', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Visual analytics', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Dashboard publishing', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Collaborative analytics', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (17, 'best_seller', NULL, 0);
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (18, 'best_seller', NULL, 1);
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (19, 'best_seller', NULL, 2);
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (20, 'best_seller', NULL, 3);
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (17, 'best_seller', 'experience', 0);
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (1, 'best_seller', 'experience', 1);
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (2, 'best_seller', 'experience', 2);
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (3, 'best_seller', 'experience', 3);
INSERT INTO listing_placements (listing_id, placement, category_id, rank) VALUES (18, 'best_seller', 'operations', 0);