INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Channel prioritisation', 4 FROM deploy_modules WHERE variant_id = 22 AND name = 'Channel Orchestration' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (22, 'Unified Customer Journey', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer journey mapping', 0 FROM deploy_modules WHERE variant_id = 22 AND name = 'Unified Customer Journey' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Personalised interactions', 1 FROM deploy_modules WHERE variant_id = 22 AND name = 'Unified Customer Journey' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Touchpoint tracking', 2 FROM deploy_modules WHERE variant_id = 22 AND name = 'Unified Customer Journey' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Journey automation', 3 FROM deploy_modules WHERE variant_id = 22 AND name = 'Unified Customer Journey' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Behaviour monitoring', 4 FROM deploy_modules WHERE variant_id = 22 AND name = 'Unified Customer Journey' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (22, 'Engagement Routing', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Smart routing', 0 FROM deploy_modules WHERE variant_id = 22 AND name = 'Engagement Routing' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Agent assignment', 1 FROM deploy_modules WHERE variant_id = 22 AND name = 'Engagement Routing' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Escalation management', 2 FROM deploy_modules WHERE variant_id = 22 AND name = 'Engagement Routing' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'SLA workflows', 3 FROM deploy_modules WHERE variant_id = 22 AND name = 'Engagement Routing' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Queue management', 4 FROM deploy_modules WHERE variant_id = 22 AND name = 'Engagement Routing' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (22, 'Experience Synchronisation', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer profile synchronisation', 0 FROM deploy_modules WHERE variant_id = 22 AND name = 'Experience Synchronisation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Real-time updates', 1 FROM deploy_modules WHERE variant_id = 22 AND name = 'Experience Synchronisation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Cross-channel continuity', 2 FROM deploy_modules WHERE variant_id = 22 AND name = 'Experience Synchronisation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Session persistence', 3 FROM deploy_modules WHERE variant_id = 22 AND name = 'Experience Synchronisation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Unified notifications', 4 FROM deploy_modules WHERE variant_id = 22 AND name = 'Experience Synchronisation' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (22, 'Customer Interaction Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Journey analytics', 0 FROM deploy_modules WHERE variant_id = 22 AND name = 'Customer Interaction Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Channel performance reporting', 1 FROM deploy_modules WHERE variant_id = 22 AND name = 'Customer Interaction Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer behaviour analytics', 2 FROM deploy_modules WHERE variant_id = 22 AND name = 'Customer Interaction Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Funnel analysis', 3 FROM deploy_modules WHERE variant_id = 22 AND name = 'Customer Interaction Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Engagement dashboards', 4 FROM deploy_modules WHERE variant_id = 22 AND name = 'Customer Interaction Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (28, 'Enterprise CMS', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Structured content management', 0 FROM deploy_modules WHERE variant_id = 28 AND name = 'Enterprise CMS' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Page composition', 1 FROM deploy_modules WHERE variant_id = 28 AND name = 'Enterprise CMS' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Version control', 2 FROM deploy_modules WHERE variant_id = 28 AND name = 'Enterprise CMS' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workflow approvals', 3 FROM deploy_modules WHERE variant_id = 28 AND name = 'Enterprise CMS' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Multi-language support', 4 FROM deploy_modules WHERE variant_id = 28 AND name = 'Enterprise CMS' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (28, 'Digital Asset Management', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Media repository', 0 FROM deploy_modules WHERE variant_id = 28 AND name = 'Digital Asset Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Asset tagging', 1 FROM deploy_modules WHERE variant_id = 28 AND name = 'Digital Asset Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Asset lifecycle management', 2 FROM deploy_modules WHERE variant_id = 28 AND name = 'Digital Asset Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'File versioning', 3 FROM deploy_modules WHERE variant_id = 28 AND name = 'Digital Asset Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Access permissions', 4 FROM deploy_modules WHERE variant_id = 28 AND name = 'Digital Asset Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (28, 'Content Workflow Engine', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Editorial workflows', 0 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Workflow Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Content approvals', 1 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Workflow Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Publishing automation', 2 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Workflow Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Review cycles', 3 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Workflow Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workflow notifications', 4 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Workflow Engine' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (28, 'Experience Personalisation', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audience segmentation', 0 FROM deploy_modules WHERE variant_id = 28 AND name = 'Experience Personalisation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Dynamic content', 1 FROM deploy_modules WHERE variant_id = 28 AND name = 'Experience Personalisation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Personalised recommendations', 2 FROM deploy_modules WHERE variant_id = 28 AND name = 'Experience Personalisation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Behaviour targeting', 3 FROM deploy_modules WHERE variant_id = 28 AND name = 'Experience Personalisation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Experience optimisation', 4 FROM deploy_modules WHERE variant_id = 28 AND name = 'Experience Personalisation' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (28, 'Content Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Content engagement analytics', 0 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Traffic reporting', 1 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Conversion analytics', 2 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audience insights', 3 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Performance dashboards', 4 FROM deploy_modules WHERE variant_id = 28 AND name = 'Content Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (34, 'Customer Management', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer profiles', 0 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Contact management', 1 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Account hierarchy', 2 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Relationship mapping', 3 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Interaction history', 4 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (34, 'Sales Pipeline Management', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Opportunity tracking', 0 FROM deploy_modules WHERE variant_id = 34 AND name = 'Sales Pipeline Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Sales stages', 1 FROM deploy_modules WHERE variant_id = 34 AND name = 'Sales Pipeline Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Forecast management', 2 FROM deploy_modules WHERE variant_id = 34 AND name = 'Sales Pipeline Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Pipeline dashboards', 3 FROM deploy_modules WHERE variant_id = 34 AND name = 'Sales Pipeline Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Revenue tracking', 4 FROM deploy_modules WHERE variant_id = 34 AND name = 'Sales Pipeline Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (34, 'Lead Management', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Lead capture', 0 FROM deploy_modules WHERE variant_id = 34 AND name = 'Lead Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Lead qualification', 1 FROM deploy_modules WHERE variant_id = 34 AND name = 'Lead Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Lead routing', 2 FROM deploy_modules WHERE variant_id = 34 AND name = 'Lead Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Scoring models', 3 FROM deploy_modules WHERE variant_id = 34 AND name = 'Lead Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign attribution', 4 FROM deploy_modules WHERE variant_id = 34 AND name = 'Lead Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (34, 'Customer Service Console', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Case management', 0 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Service Console' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'SLA management', 1 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Service Console' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Ticket routing', 2 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Service Console' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Knowledge integration', 3 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Service Console' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Service workflows', 4 FROM deploy_modules WHERE variant_id = 34 AND name = 'Customer Service Console' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (34, 'CRM Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Sales dashboards', 0 FROM deploy_modules WHERE variant_id = 34 AND name = 'CRM Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer insights', 1 FROM deploy_modules WHERE variant_id = 34 AND name = 'CRM Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Forecast reporting', 2 FROM deploy_modules WHERE variant_id = 34 AND name = 'CRM Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Pipeline analytics', 3 FROM deploy_modules WHERE variant_id = 34 AND name = 'CRM Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Activity monitoring', 4 FROM deploy_modules WHERE variant_id = 34 AND name = 'CRM Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (40, 'Campaign Automation', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign workflows', 0 FROM deploy_modules WHERE variant_id = 40 AND name = 'Campaign Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Multi-step campaigns', 1 FROM deploy_modules WHERE variant_id = 40 AND name = 'Campaign Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Trigger automation', 2 FROM deploy_modules WHERE variant_id = 40 AND name = 'Campaign Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audience targeting', 3 FROM deploy_modules WHERE variant_id = 40 AND name = 'Campaign Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign approvals', 4 FROM deploy_modules WHERE variant_id = 40 AND name = 'Campaign Automation' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (40, 'Customer Journey Automation', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Journey orchestration', 0 FROM deploy_modules WHERE variant_id = 40 AND name = 'Customer Journey Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Behaviour-based workflows', 1 FROM deploy_modules WHERE variant_id = 40 AND name = 'Customer Journey Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Event triggers', 2 FROM deploy_modules WHERE variant_id = 40 AND name = 'Customer Journey Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Personalised engagement', 3 FROM deploy_modules WHERE variant_id = 40 AND name = 'Customer Journey Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Lifecycle management', 4 FROM deploy_modules WHERE variant_id = 40 AND name = 'Customer Journey Automation' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (40, 'Lead Nurturing Engine', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Lead scoring', 0 FROM deploy_modules WHERE variant_id = 40 AND name = 'Lead Nurturing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Drip campaigns', 1 FROM deploy_modules WHERE variant_id = 40 AND name = 'Lead Nurturing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Segmentation', 2 FROM deploy_modules WHERE variant_id = 40 AND name = 'Lead Nurturing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Qualification workflows', 3 FROM deploy_modules WHERE variant_id = 40 AND name = 'Lead Nurturing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Conversion tracking', 4 FROM deploy_modules WHERE variant_id = 40 AND name = 'Lead Nurturing Engine' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (40, 'Email Marketing Suite', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Email builder', 0 FROM deploy_modules WHERE variant_id = 40 AND name = 'Email Marketing Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Email templates', 1 FROM deploy_modules WHERE variant_id = 40 AND name = 'Email Marketing Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'A/B testing', 2 FROM deploy_modules WHERE variant_id = 40 AND name = 'Email Marketing Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Delivery management', 3 FROM deploy_modules WHERE variant_id = 40 AND name = 'Email Marketing Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Open/click tracking', 4 FROM deploy_modules WHERE variant_id = 40 AND name = 'Email Marketing Suite' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (40, 'Marketing Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Campaign performance', 0 FROM deploy_modules WHERE variant_id = 40 AND name = 'Marketing Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'ROI dashboards', 1 FROM deploy_modules WHERE variant_id = 40 AND name = 'Marketing Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audience insights', 2 FROM deploy_modules WHERE variant_id = 40 AND name = 'Marketing Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Attribution analytics', 3 FROM deploy_modules WHERE variant_id = 40 AND name = 'Marketing Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Funnel analytics', 4 FROM deploy_modules WHERE variant_id = 40 AND name = 'Marketing Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (46, 'Product Configuration', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Product catalogues', 0 FROM deploy_modules WHERE variant_id = 46 AND name = 'Product Configuration' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Rules-based configuration', 1 FROM deploy_modules WHERE variant_id = 46 AND name = 'Product Configuration' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Bundle management', 2 FROM deploy_modules WHERE variant_id = 46 AND name = 'Product Configuration' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Guided selling', 3 FROM deploy_modules WHERE variant_id = 46 AND name = 'Product Configuration' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compatibility validation', 4 FROM deploy_modules WHERE variant_id = 46 AND name = 'Product Configuration' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (46, 'Pricing Engine', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Dynamic pricing', 0 FROM deploy_modules WHERE variant_id = 46 AND name = 'Pricing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Discount management', 1 FROM deploy_modules WHERE variant_id = 46 AND name = 'Pricing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Pricing rules', 2 FROM deploy_modules WHERE variant_id = 46 AND name = 'Pricing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Contract pricing', 3 FROM deploy_modules WHERE variant_id = 46 AND name = 'Pricing Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Margin controls', 4 FROM deploy_modules WHERE variant_id = 46 AND name = 'Pricing Engine' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (46, 'Quote Management', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Quote generation', 0 FROM deploy_modules WHERE variant_id = 46 AND name = 'Quote Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Proposal templates', 1 FROM deploy_modules WHERE variant_id = 46 AND name = 'Quote Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Version management', 2 FROM deploy_modules WHERE variant_id = 46 AND name = 'Quote Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer approvals', 3 FROM deploy_modules WHERE variant_id = 46 AND name = 'Quote Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Digital signatures', 4 FROM deploy_modules WHERE variant_id = 46 AND name = 'Quote Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (46, 'Approval Workflows', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Pricing approvals', 0 FROM deploy_modules WHERE variant_id = 46 AND name = 'Approval Workflows' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Escalation workflows', 1 FROM deploy_modules WHERE variant_id = 46 AND name = 'Approval Workflows' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compliance checks', 2 FROM deploy_modules WHERE variant_id = 46 AND name = 'Approval Workflows' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audit tracking', 3 FROM deploy_modules WHERE variant_id = 46 AND name = 'Approval Workflows' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Approval notifications', 4 FROM deploy_modules WHERE variant_id = 46 AND name = 'Approval Workflows' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (46, 'CPQ Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Quote analytics', 0 FROM deploy_modules WHERE variant_id = 46 AND name = 'CPQ Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Sales performance reporting', 1 FROM deploy_modules WHERE variant_id = 46 AND name = 'CPQ Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Pricing insights', 2 FROM deploy_modules WHERE variant_id = 46 AND name = 'CPQ Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Approval metrics', 3 FROM deploy_modules WHERE variant_id = 46 AND name = 'CPQ Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Revenue dashboards', 4 FROM deploy_modules WHERE variant_id = 46 AND name = 'CPQ Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (52, 'Service Desk', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Service request handling', 0 FROM deploy_modules WHERE variant_id = 52 AND name = 'Service Desk' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Queue management', 1 FROM deploy_modules WHERE variant_id = 52 AND name = 'Service Desk' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'SLA tracking', 2 FROM deploy_modules WHERE variant_id = 52 AND name = 'Service Desk' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Escalation workflows', 3 FROM deploy_modules WHERE variant_id = 52 AND name = 'Service Desk' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Agent workspace', 4 FROM deploy_modules WHERE variant_id = 52 AND name = 'Service Desk' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (52, 'Ticket Management', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Ticket lifecycle management', 0 FROM deploy_modules WHERE variant_id = 52 AND name = 'Ticket Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Categorisation', 1 FROM deploy_modules WHERE variant_id = 52 AND name = 'Ticket Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Priority routing', 2 FROM deploy_modules WHERE variant_id = 52 AND name = 'Ticket Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Assignment workflows', 3 FROM deploy_modules WHERE variant_id = 52 AND name = 'Ticket Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Resolution tracking', 4 FROM deploy_modules WHERE variant_id = 52 AND name = 'Ticket Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (52, 'Customer Communication Hub', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Omnichannel support', 0 FROM deploy_modules WHERE variant_id = 52 AND name = 'Customer Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Live chat', 1 FROM deploy_modules WHERE variant_id = 52 AND name = 'Customer Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Email integration', 2 FROM deploy_modules WHERE variant_id = 52 AND name = 'Customer Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Messaging integration', 3 FROM deploy_modules WHERE variant_id = 52 AND name = 'Customer Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Notification management', 4 FROM deploy_modules WHERE variant_id = 52 AND name = 'Customer Communication Hub' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (52, 'Knowledge Base', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Knowledge articles', 0 FROM deploy_modules WHERE variant_id = 52 AND name = 'Knowledge Base' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Self-service portal', 1 FROM deploy_modules WHERE variant_id = 52 AND name = 'Knowledge Base' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'FAQ management', 2 FROM deploy_modules WHERE variant_id = 52 AND name = 'Knowledge Base' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Search capability', 3 FROM deploy_modules WHERE variant_id = 52 AND name = 'Knowledge Base' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Content approvals', 4 FROM deploy_modules WHERE variant_id = 52 AND name = 'Knowledge Base' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (52, 'Support Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Resolution metrics', 0 FROM deploy_modules WHERE variant_id = 52 AND name = 'Support Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'SLA reporting', 1 FROM deploy_modules WHERE variant_id = 52 AND name = 'Support Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Agent performance', 2 FROM deploy_modules WHERE variant_id = 52 AND name = 'Support Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Customer satisfaction tracking', 3 FROM deploy_modules WHERE variant_id = 52 AND name = 'Support Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Support dashboards', 4 FROM deploy_modules WHERE variant_id = 52 AND name = 'Support Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Collaboration Workspace', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Team workspaces', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'File collaboration', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Shared calendars', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Meeting integration', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workspace permissions', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Collaboration Workspace' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Employee Communication Hub', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Announcements', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Internal messaging', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Employee engagement feeds', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Notifications', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Broadcast communications', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Employee Communication Hub' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Knowledge Workspace', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Knowledge repositories', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Document management', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Search capabilities', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Knowledge sharing', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Content governance', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Knowledge Workspace' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Task & Activity Management', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Task assignment', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workflow tracking', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Activity monitoring', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Team coordination', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Productivity tracking', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Task & Activity Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (58, 'Workplace Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Usage reporting', 0 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Collaboration analytics', 1 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Engagement insights', 2 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Productivity dashboards', 3 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Adoption monitoring', 4 FROM deploy_modules WHERE variant_id = 58 AND name = 'Workplace Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (94, 'Finance Management', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'General ledger', 0 FROM deploy_modules WHERE variant_id = 94 AND name = 'Finance Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Accounts payable', 1 FROM deploy_modules WHERE variant_id = 94 AND name = 'Finance Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Accounts receivable', 2 FROM deploy_modules WHERE variant_id = 94 AND name = 'Finance Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Budget management', 3 FROM deploy_modules WHERE variant_id = 94 AND name = 'Finance Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Financial reporting', 4 FROM deploy_modules WHERE variant_id = 94 AND name = 'Finance Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (94, 'Procurement Management', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Purchase requests', 0 FROM deploy_modules WHERE variant_id = 94 AND name = 'Procurement Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Vendor management', 1 FROM deploy_modules WHERE variant_id = 94 AND name = 'Procurement Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Procurement approvals', 2 FROM deploy_modules WHERE variant_id = 94 AND name = 'Procurement Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Contract tracking', 3 FROM deploy_modules WHERE variant_id = 94 AND name = 'Procurement Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Supplier workflows', 4 FROM deploy_modules WHERE variant_id = 94 AND name = 'Procurement Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (94, 'Inventory Management', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Inventory tracking', 0 FROM deploy_modules WHERE variant_id = 94 AND name = 'Inventory Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Warehouse management', 1 FROM deploy_modules WHERE variant_id = 94 AND name = 'Inventory Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Stock monitoring', 2 FROM deploy_modules WHERE variant_id = 94 AND name = 'Inventory Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Inventory forecasting', 3 FROM deploy_modules WHERE variant_id = 94 AND name = 'Inventory Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Reorder automation', 4 FROM deploy_modules WHERE variant_id = 94 AND name = 'Inventory Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (94, 'Operations Management', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Operational workflows', 0 FROM deploy_modules WHERE variant_id = 94 AND name = 'Operations Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Resource planning', 1 FROM deploy_modules WHERE variant_id = 94 AND name = 'Operations Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Process management', 2 FROM deploy_modules WHERE variant_id = 94 AND name = 'Operations Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Operational reporting', 3 FROM deploy_modules WHERE variant_id = 94 AND name = 'Operations Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workflow approvals', 4 FROM deploy_modules WHERE variant_id = 94 AND name = 'Operations Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (94, 'ERP Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Executive dashboards', 0 FROM deploy_modules WHERE variant_id = 94 AND name = 'ERP Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Operational reporting', 1 FROM deploy_modules WHERE variant_id = 94 AND name = 'ERP Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Financial analytics', 2 FROM deploy_modules WHERE variant_id = 94 AND name = 'ERP Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'KPI monitoring', 3 FROM deploy_modules WHERE variant_id = 94 AND name = 'ERP Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Forecast analytics', 4 FROM deploy_modules WHERE variant_id = 94 AND name = 'ERP Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (100, 'Workforce Scheduling', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Shift scheduling', 0 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Scheduling' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workforce planning', 1 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Scheduling' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Availability management', 2 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Scheduling' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Scheduling optimisation', 3 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Scheduling' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Shift notifications', 4 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Scheduling' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (100, 'Attendance Management', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Time tracking', 0 FROM deploy_modules WHERE variant_id = 100 AND name = 'Attendance Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Leave management', 1 FROM deploy_modules WHERE variant_id = 100 AND name = 'Attendance Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Attendance monitoring', 2 FROM deploy_modules WHERE variant_id = 100 AND name = 'Attendance Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Overtime tracking', 3 FROM deploy_modules WHERE variant_id = 100 AND name = 'Attendance Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compliance reporting', 4 FROM deploy_modules WHERE variant_id = 100 AND name = 'Attendance Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (100, 'Workforce Operations', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workforce coordination', 0 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Operations' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Task allocation', 1 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Operations' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Operational workflows', 2 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Operations' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workforce communication', 3 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Operations' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Activity monitoring', 4 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Operations' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (100, 'Employee Self-Service', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Leave requests', 0 FROM deploy_modules WHERE variant_id = 100 AND name = 'Employee Self-Service' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Shift swaps', 1 FROM deploy_modules WHERE variant_id = 100 AND name = 'Employee Self-Service' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Personal profile management', 2 FROM deploy_modules WHERE variant_id = 100 AND name = 'Employee Self-Service' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Notifications', 3 FROM deploy_modules WHERE variant_id = 100 AND name = 'Employee Self-Service' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Self-service workflows', 4 FROM deploy_modules WHERE variant_id = 100 AND name = 'Employee Self-Service' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (100, 'Workforce Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workforce dashboards', 0 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Productivity analytics', 1 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Attendance insights', 2 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Labour forecasting', 3 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compliance analytics', 4 FROM deploy_modules WHERE variant_id = 100 AND name = 'Workforce Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Data Integration Platform', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'ETL/ELT pipelines', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'API integrations', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data synchronisation', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Batch processing', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Real-time streaming', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Integration Platform' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Data Governance Hub', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data catalogues', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data lineage', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Access controls', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data quality monitoring', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Governance workflows', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Governance Hub' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Data Warehouse', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Centralised storage', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data modelling', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Query optimisation', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Historical data management', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data partitioning', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Warehouse' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Master Data Management', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Golden record management', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data standardisation', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Duplicate management', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Entity resolution', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Reference data management', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Master Data Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (106, 'Data Analytics Workspace', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Query workspaces', 0 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data exploration', 1 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Visual analytics', 2 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Dashboard publishing', 3 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Collaborative analytics', 4 FROM deploy_modules WHERE variant_id = 106 AND name = 'Data Analytics Workspace' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (112, 'BI Dashboarding', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Interactive dashboards', 0 FROM deploy_modules WHERE variant_id = 112 AND name = 'BI Dashboarding' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'KPI monitoring', 1 FROM deploy_modules WHERE variant_id = 112 AND name = 'BI Dashboarding' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Drill-down analytics', 2 FROM deploy_modules WHERE variant_id = 112 AND name = 'BI Dashboarding' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Real-time reporting', 3 FROM deploy_modules WHERE variant_id = 112 AND name = 'BI Dashboarding' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Dashboard sharing', 4 FROM deploy_modules WHERE variant_id = 112 AND name = 'BI Dashboarding' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (112, 'Reporting Workspace', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Report generation', 0 FROM deploy_modules WHERE variant_id = 112 AND name = 'Reporting Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Scheduled reporting', 1 FROM deploy_modules WHERE variant_id = 112 AND name = 'Reporting Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Export capabilities', 2 FROM deploy_modules WHERE variant_id = 112 AND name = 'Reporting Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Ad hoc reporting', 3 FROM deploy_modules WHERE variant_id = 112 AND name = 'Reporting Workspace' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Report approvals', 4 FROM deploy_modules WHERE variant_id = 112 AND name = 'Reporting Workspace' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (112, 'Data Visualisation Suite', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Chart libraries', 0 FROM deploy_modules WHERE variant_id = 112 AND name = 'Data Visualisation Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Visual storytelling', 1 FROM deploy_modules WHERE variant_id = 112 AND name = 'Data Visualisation Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data exploration', 2 FROM deploy_modules WHERE variant_id = 112 AND name = 'Data Visualisation Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Interactive filtering', 3 FROM deploy_modules WHERE variant_id = 112 AND name = 'Data Visualisation Suite' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Custom visualisations', 4 FROM deploy_modules WHERE variant_id = 112 AND name = 'Data Visualisation Suite' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (112, 'Executive Intelligence Hub', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Executive scorecards', 0 FROM deploy_modules WHERE variant_id = 112 AND name = 'Executive Intelligence Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Strategic insights', 1 FROM deploy_modules WHERE variant_id = 112 AND name = 'Executive Intelligence Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Trend analysis', 2 FROM deploy_modules WHERE variant_id = 112 AND name = 'Executive Intelligence Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Performance forecasting', 3 FROM deploy_modules WHERE variant_id = 112 AND name = 'Executive Intelligence Hub' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Decision support', 4 FROM deploy_modules WHERE variant_id = 112 AND name = 'Executive Intelligence Hub' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (112, 'Analytics Governance', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Access management', 0 FROM deploy_modules WHERE variant_id = 112 AND name = 'Analytics Governance' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Data governance policies', 1 FROM deploy_modules WHERE variant_id = 112 AND name = 'Analytics Governance' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audit logging', 2 FROM deploy_modules WHERE variant_id = 112 AND name = 'Analytics Governance' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Analytics approvals', 3 FROM deploy_modules WHERE variant_id = 112 AND name = 'Analytics Governance' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compliance monitoring', 4 FROM deploy_modules WHERE variant_id = 112 AND name = 'Analytics Governance' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (118, 'AI Assistant Framework', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Conversational AI', 0 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Assistant Framework' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Copilot experiences', 1 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Assistant Framework' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Context-aware assistance', 2 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Assistant Framework' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Multilingual support', 3 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Assistant Framework' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'AI interaction history', 4 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Assistant Framework' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (118, 'AI Agent Platform', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Autonomous workflows', 0 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Agent Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Task orchestration', 1 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Agent Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Agent configuration', 2 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Agent Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Human-in-the-loop controls', 3 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Agent Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Agent monitoring', 4 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Agent Platform' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (118, 'Enterprise Knowledge AI', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Enterprise search', 0 FROM deploy_modules WHERE variant_id = 118 AND name = 'Enterprise Knowledge AI' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Knowledge retrieval', 1 FROM deploy_modules WHERE variant_id = 118 AND name = 'Enterprise Knowledge AI' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Semantic indexing', 2 FROM deploy_modules WHERE variant_id = 118 AND name = 'Enterprise Knowledge AI' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Document intelligence', 3 FROM deploy_modules WHERE variant_id = 118 AND name = 'Enterprise Knowledge AI' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Context grounding', 4 FROM deploy_modules WHERE variant_id = 118 AND name = 'Enterprise Knowledge AI' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (118, 'AI Automation Engine', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Workflow automation', 0 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Automation Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'AI decision routing', 1 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Automation Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Trigger-based actions', 2 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Automation Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Process augmentation', 3 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Automation Engine' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Automation monitoring', 4 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Automation Engine' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (118, 'AI Governance & Monitoring', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'AI audit trails', 0 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Governance & Monitoring' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Model monitoring', 1 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Governance & Monitoring' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Prompt governance', 2 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Governance & Monitoring' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compliance controls', 3 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Governance & Monitoring' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Usage analytics', 4 FROM deploy_modules WHERE variant_id = 118 AND name = 'AI Governance & Monitoring' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (124, 'IT Governance Framework', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Governance structures', 0 FROM deploy_modules WHERE variant_id = 124 AND name = 'IT Governance Framework' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Control frameworks', 1 FROM deploy_modules WHERE variant_id = 124 AND name = 'IT Governance Framework' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Operating models', 2 FROM deploy_modules WHERE variant_id = 124 AND name = 'IT Governance Framework' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Approval workflows', 3 FROM deploy_modules WHERE variant_id = 124 AND name = 'IT Governance Framework' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Policy mapping', 4 FROM deploy_modules WHERE variant_id = 124 AND name = 'IT Governance Framework' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (124, 'Policy Management', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Policy repositories', 0 FROM deploy_modules WHERE variant_id = 124 AND name = 'Policy Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Version management', 1 FROM deploy_modules WHERE variant_id = 124 AND name = 'Policy Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Policy approvals', 2 FROM deploy_modules WHERE variant_id = 124 AND name = 'Policy Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Policy attestations', 3 FROM deploy_modules WHERE variant_id = 124 AND name = 'Policy Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Policy lifecycle tracking', 4 FROM deploy_modules WHERE variant_id = 124 AND name = 'Policy Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (124, 'Risk & Compliance Controls', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Risk registers', 0 FROM deploy_modules WHERE variant_id = 124 AND name = 'Risk & Compliance Controls' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compliance workflows', 1 FROM deploy_modules WHERE variant_id = 124 AND name = 'Risk & Compliance Controls' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Control testing', 2 FROM deploy_modules WHERE variant_id = 124 AND name = 'Risk & Compliance Controls' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Exception management', 3 FROM deploy_modules WHERE variant_id = 124 AND name = 'Risk & Compliance Controls' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compliance tracking', 4 FROM deploy_modules WHERE variant_id = 124 AND name = 'Risk & Compliance Controls' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (124, 'Technology Audit Management', 3);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audit planning', 0 FROM deploy_modules WHERE variant_id = 124 AND name = 'Technology Audit Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Evidence collection', 1 FROM deploy_modules WHERE variant_id = 124 AND name = 'Technology Audit Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audit workflows', 2 FROM deploy_modules WHERE variant_id = 124 AND name = 'Technology Audit Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Findings management', 3 FROM deploy_modules WHERE variant_id = 124 AND name = 'Technology Audit Management' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Remediation tracking', 4 FROM deploy_modules WHERE variant_id = 124 AND name = 'Technology Audit Management' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (124, 'Governance Analytics', 4);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Compliance dashboards', 0 FROM deploy_modules WHERE variant_id = 124 AND name = 'Governance Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Risk analytics', 1 FROM deploy_modules WHERE variant_id = 124 AND name = 'Governance Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Audit reporting', 2 FROM deploy_modules WHERE variant_id = 124 AND name = 'Governance Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Governance KPIs', 3 FROM deploy_modules WHERE variant_id = 124 AND name = 'Governance Analytics' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Executive insights', 4 FROM deploy_modules WHERE variant_id = 124 AND name = 'Governance Analytics' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (130, 'CI/CD Pipeline Platform', 0);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Build pipelines', 0 FROM deploy_modules WHERE variant_id = 130 AND name = 'CI/CD Pipeline Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Release automation', 1 FROM deploy_modules WHERE variant_id = 130 AND name = 'CI/CD Pipeline Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Deployment orchestration', 2 FROM deploy_modules WHERE variant_id = 130 AND name = 'CI/CD Pipeline Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Version control integration', 3 FROM deploy_modules WHERE variant_id = 130 AND name = 'CI/CD Pipeline Platform' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Pipeline monitoring', 4 FROM deploy_modules WHERE variant_id = 130 AND name = 'CI/CD Pipeline Platform' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (130, 'Infrastructure Automation', 1);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Infrastructure-as-code', 0 FROM deploy_modules WHERE variant_id = 130 AND name = 'Infrastructure Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Environment provisioning', 1 FROM deploy_modules WHERE variant_id = 130 AND name = 'Infrastructure Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Configuration management', 2 FROM deploy_modules WHERE variant_id = 130 AND name = 'Infrastructure Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Cloud orchestration', 3 FROM deploy_modules WHERE variant_id = 130 AND name = 'Infrastructure Automation' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Automation templates', 4 FROM deploy_modules WHERE variant_id = 130 AND name = 'Infrastructure Automation' LIMIT 1;
INSERT INTO deploy_modules (variant_id, name, sort_order) VALUES (130, 'Security Operations', 2);
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Security scanning', 0 FROM deploy_modules WHERE variant_id = 130 AND name = 'Security Operations' LIMIT 1;
INSERT INTO deploy_module_features (module_id, feature_text, sort_order) SELECT id, 'Vulnerability management', 1 FROM deploy_modules WHERE variant_id = 130 AND name = 'Security Operations' LIMIT 1;
