import { lazy } from "react";

export const IndexProductLanding = lazy(() => import("@/pages/IndexProductLanding"));
export const IndexTraditional = lazy(() => import("@/pages/IndexTraditional"));
export const Index = lazy(() => import("@/pages/Index"));
export const Explore = lazy(() => import("@/pages/Explore"));
export const Marketplace = lazy(() => import("@/pages/Marketplace"));
export const ServiceDetail = lazy(() => import("@/pages/ServiceDetail"));
export const Contact = lazy(() => import("@/pages/Contact"));
export const ButlerDemo = lazy(() => import("@/pages/ButlerDemo"));
export const Cart = lazy(() => import("@/pages/Cart"));
export const SignIn = lazy(() => import("@/pages/auth/SignIn"));
export const ProfileSetup = lazy(() => import("@/pages/onboarding/ProfileSetup"));
export const OrganisationAccess = lazy(() => import("@/pages/onboarding/OrganisationAccess"));
export const OrganisationSetup = lazy(() => import("@/pages/onboarding/OrganisationSetup"));
export const Complete = lazy(() => import("@/pages/onboarding/Complete"));
export const Legal = lazy(() => import("@/pages/legal/Legal"));
export const Terms = lazy(() => import("@/pages/legal/Terms"));
export const Privacy = lazy(() => import("@/pages/legal/Privacy"));
export const FAQ = lazy(() => import("@/pages/legal/FAQ"));
export const Overview = lazy(() => import("@/pages/dashboard/Overview"));
export const ActiveServices = lazy(() => import("@/pages/dashboard/ActiveServices"));
export const OrganisationProfile = lazy(() => import("@/pages/dashboard/OrganisationProfile"));
export const EngagementDetail = lazy(() => import("@/pages/dashboard/EngagementDetail"));
export const ServiceOrders = lazy(() => import("@/pages/dashboard/ServiceOrders"));
export const ServiceOrderDetail = lazy(() => import("@/pages/dashboard/ServiceOrderDetail"));
export const CustomerServiceOrders = lazy(() => import("@/pages/dashboard/customer/ServiceOrders"));
export const CustomerServiceOrderDetail = lazy(
  () => import("@/pages/dashboard/customer/ServiceOrderDetail")
);
export const Inbox = lazy(() => import("@/pages/dashboard/Inbox"));
export const Notifications = lazy(() => import("@/pages/dashboard/Notifications"));
export const OrganisationAdmin = lazy(() => import("@/pages/dashboard/OrganisationAdmin"));
export const Calendar = lazy(() => import("@/pages/dashboard/Calendar"));
export const Documents = lazy(() => import("@/pages/dashboard/Documents"));
export const Settings = lazy(() => import("@/pages/dashboard/Settings"));
export const Support = lazy(() => import("@/pages/dashboard/Support"));
export const HelpCentre = lazy(() => import("@/pages/dashboard/HelpCentre"));
export const Organisations = lazy(() => import("@/pages/dashboard/Organisations"));
export const Users = lazy(() => import("@/pages/dashboard/Users"));
export const Catalogue = lazy(() => import("@/pages/dashboard/Catalogue"));
export const HelpContent = lazy(() => import("@/pages/dashboard/HelpContent"));
export const DqPortfolio = lazy(() => import("@/pages/dashboard/dq/Portfolio"));
export const DqFinance = lazy(() => import("@/pages/dashboard/dq/Finance"));
export const DqSupportOps = lazy(() => import("@/pages/dashboard/dq/SupportOps"));
export const DqQueue = lazy(() => import("@/pages/dashboard/dq/Queue"));
export const DqInvoices = lazy(() => import("@/pages/dashboard/dq/Invoices"));
export const DqOnboarding = lazy(() => import("@/pages/dashboard/dq/Onboarding"));
export const CatalogRouteLayout = lazy(() => import("@/layouts/CatalogRouteLayout"));
export const ChatButton = lazy(() => import("@/components/ChatButton"));
export const CartDrawer = lazy(() => import("@/components/cart/CartDrawer"));
export const NotFound = lazy(() => import("@/pages/NotFound"));
