/** Fallback stored when the customer leaves additional details blank. */
export const AUTO_GENERATED_REQUEST_DESCRIPTION_PREFIX =
  "Service requested via TMaaS marketplace:";

export function buildStoredRequestDescription(serviceName: string, notes?: string): string {
  const trimmed = notes?.trim();
  if (trimmed) return trimmed;
  return `${AUTO_GENERATED_REQUEST_DESCRIPTION_PREFIX} ${serviceName}`;
}

export function isAutoGeneratedRequestDescription(description: string): boolean {
  return description.trim().startsWith(AUTO_GENERATED_REQUEST_DESCRIPTION_PREFIX);
}

/** Customer free-text from the request form; null when only the auto-generated fallback was stored. */
export function getCustomerSubmittedNotes(description: string): string | null {
  const trimmed = description.trim();
  if (!trimmed || isAutoGeneratedRequestDescription(trimmed)) return null;
  return trimmed;
}
