import { describe, expect, it } from "vitest";
import {
  AUTO_GENERATED_REQUEST_DESCRIPTION_PREFIX,
  buildStoredRequestDescription,
  getCustomerSubmittedNotes,
  isAutoGeneratedRequestDescription,
} from "@/lib/requests/customerRequestNotes";

describe("customerRequestNotes", () => {
  it("stores trimmed customer notes when provided", () => {
    expect(buildStoredRequestDescription("AI Readiness Assessment", "  Need Q3 delivery  ")).toBe(
      "Need Q3 delivery",
    );
  });

  it("stores an auto-generated fallback when notes are empty", () => {
    const stored = buildStoredRequestDescription("AI Readiness Assessment");
    expect(stored).toBe(
      `${AUTO_GENERATED_REQUEST_DESCRIPTION_PREFIX} AI Readiness Assessment`,
    );
    expect(isAutoGeneratedRequestDescription(stored)).toBe(true);
    expect(getCustomerSubmittedNotes(stored)).toBeNull();
  });

  it("returns customer notes and ignores auto-generated fallback text", () => {
    expect(getCustomerSubmittedNotes("These are additional dets")).toBe("These are additional dets");
    expect(
      getCustomerSubmittedNotes(
        `${AUTO_GENERATED_REQUEST_DESCRIPTION_PREFIX} AI Readiness Assessment`,
      ),
    ).toBeNull();
  });
});
